### ISSUE TITLE
cannot build git

### ISSUE THREAD

**Issue by xevilstar** [tuxedocomputers/tuxedo-control-center#200]
npm --version 
8.11.0

node --version
v16.14.2

cat /etc/debian_version 
bookworm/sid

> tuxedo-control-center@1.1.4 postinstall
> electron-builder install-app-deps

  • electron-builder version=20.44.4
  • rebuilding native production dependencies platform=linux arch=x64
Error: /usr/bin/node exited with code 1
Error output:
npm ERR! code 1
npm ERR! path /usr/src/tuxedo-control-center/node_modules/abstract-socket
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
npm ERR! gyp http GET https://atom.io/download/electron/v13.6.9/node-v13.6.9-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack TypeError: fetch is not a function
npm ERR! gyp ERR! stack     at download (/usr/share/nodejs/node-gyp/lib/install.js:354:21)
npm ERR! gyp ERR! stack     at go (/usr/share/nodejs/node-gyp/lib/install.js:150:27)
npm ERR! gyp ERR! stack     at async install (/usr/share/nodejs/node-gyp/lib/install.js:62:18)
npm ERR! gyp ERR! System Linux 5.18.1-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/src/tuxedo-control-center/node_modules/abstract-socket
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-03T13_48_12_444Z-debug-0.log

    at ChildProcess.<anonymous> (/usr/src/tuxedo-control-center/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at _rebuild (/usr/src/tuxedo-control-center/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/usr/src/tuxedo-control-center/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /usr/src/tuxedo-control-center/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at _installOrRebuild (/usr/src/tuxedo-control-center/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/usr/src/tuxedo-control-center/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /usr/src/tuxedo-control-center/node_modules/electron-builder/src/cli/install-app-deps.ts:58:9
    at Generator.next (<anonymous>)
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at _installAppDeps (/usr/src/tuxedo-control-center/node_modules/electron-builder/out/cli/install-app-deps.js:177:26)
    at installAppDeps (/usr/src/tuxedo-control-center/node_modules/electron-builder/out/cli/install-app-deps.js:146:26)
    at /usr/src/tuxedo-control-center/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code 1
npm ERR! path /usr/src/tuxedo-control-center
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-03T13_47_24_015Z-debug-0.log

**Comment by tuxedoder** [comment]
I tried to build on debian 12 myself and I got it working. More information is [here](https://github.com/tuxedocomputers/tuxedo-control-center/issues/130#issuecomment-1969902343). Make sure you use the mentioned versions.
