### ISSUE TITLE
Please provide build instructions for package maitainers

### ISSUE THREAD

**Issue by yochananmarqos** [tuxedocomputers/tuxedo-control-center#212]
The Gentoo, Manjaro and AUR packages are all packaged from the binary RPM build. Package maintainers should be able to create [reproducible builds](https://reproducible-builds.org/).

Running the following should work, however if one does, the package is broken.

```
npm install
npm run pack-prod deb
```

```
❯ tuxedo-control-center --trace-warnings
/bin/sh: line 1: prime-select: command not found
/bin/sh: line 1: prime-supported: command not found
(node:1357607) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:207:24)
    at /opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/e-app/main.js:176:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `tuxedo-control-center --trace-warnings ...` to show where the warning was created)
(node:1357607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1357607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: polyfills-es2015.4013601fd8cfd4c8c85f.js:1:12102
```

**Comment by tuxedoder** [comment]
We build our packages with the provided commands. 
```
npm i
npm run pack-prod deb
```
The build itself worked in your case, but tccd was not available and thus tcc can not start. Make sure that the tccd service is running with `sudo ./tccd --start`.

**Comment by yochananmarqos** [comment]
Yes, I figured it out on my own several months ago and have been building it from source on Manjaro since. Thanks anyway.
