### ISSUE TITLE
1.1.4 and later don't work on runit

### ISSUE THREAD

**Issue by TheHighGroundWins** [tuxedocomputers/tuxedo-control-center#216]
```
events.js:292
      throw er; // Unhandled 'error' event
      ^
 
Error: read ENOTCONN
    at tryReadStart (net.js:571:20)
    at ReadStream.Socket._read (net.js:582:5)
    at ReadStream.Readable.read (_stream_readable.js:474:10)
    at ReadStream.Socket.read (net.js:622:39)
    at ReadStream.Socket (net.js:374:12)
    at new ReadStream (tty.js:58:14)
    at process.getStdin [as stdin] (internal/bootstrap/switches/is_main_thread.js:147:15)
    at get (<anonymous>)
    at getOwn (internal/bootstrap/loaders.js:150:5)
    at NativeModule.syncExports (internal/bootstrap/loaders.js:258:31)
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1489:13)
    at internal/main/run_main_module.js:17:47 {
  errno: -107,
  code: 'ENOTCONN',
  syscall: 'read'
}
```

this is the JS error I get in my logs.

**Comment by Homo-carbonis** [comment]
This is still an issue for me. Since tccd works normally when started manually from a tty I am struggling to work out what is different when it is started by runit. exec -c makes no difference, nor does running with sh -i.

**Comment by TheHighGroundWins** [comment]
The latest version of tuxedo control center runs due to this runit script

https://aur.archlinux.org/cgit/aur.git/tree/tccd.run?h=tuxedo-control-center-runit

from the following aur package
https://aur.archlinux.org/packages/tuxedo-control-center-runit

Credit to Kristofers_Solo
