### ISSUE TITLE
Doesn't work with Node 18. Got a libva error with node 16.

### ISSUE THREAD

**Issue by code3z** [tuxedocomputers/tuxedo-control-center#238]
I'm using fedora. Here's the error:
```
[ian@fedora tuxedo-control-center]$ npm run start

> tuxedo-control-center@1.2.2 start
> electron ./dist/tuxedo-control-center

Config file (/home/ian/.tcc/user.conf) does not exist. Will be created.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
/bin/sh: line 1: prime-select: command not found
/bin/sh: line 1: prime-supported: command not found
(node:30610) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/home/ian/tuxedo-control-center/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:257:24)
    at /home/ian/tuxedo-control-center/dist/tuxedo-control-center/e-app/e-app/main.js:179:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:30610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: polyfills-es2015.js:868:30
^C/home/ian/tuxedo-control-center/node_modules/electron/dist/electron exited with signal SIGINT
[ian@fedora tuxedo-control-center]$ npm run start

> tuxedo-control-center@1.2.2 start
> electron ./dist/tuxedo-control-center

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
/bin/sh: line 1: prime-select: command not found
/bin/sh: line 1: prime-supported: command not found
(node:30749) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/home/ian/tuxedo-control-center/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:257:24)
    at /home/ian/tuxedo-control-center/dist/tuxedo-control-center/e-app/e-app/main.js:179:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:30749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: polyfills-es2015.js:868:30
```

**Comment by EpicWink** [comment]
Using OS's Node v18

<details>
<summary>Git diff</summary>

```diff
diff --git a/package.json b/package.json
index 45544e2..9ac6c29 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "build-ng-prod": "npm run copy-changelog && ng build --prod",
     "build-electron": "tsc -p ./src/e-app",
     "build-service": "tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service",
-    "bundle-service": "pkg --target node14-linux-x64 --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json",
+    "bundle-service": "pkg --target host --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json",
     "build-native": "node-gyp configure && node-gyp rebuild",
     "copy-files": "run-s copy-package-json copy-dist-files copy-native copy-cameractls copy-udev-rule",
     "copy-native": "mkdir -p ./dist/tuxedo-control-center/service-app/native-lib && cp ./build/Release/TuxedoIOAPI.node ./dist/tuxedo-control-center/data/service",
```

</details>

I had to compile with `--openssl-legacy-provider`:
```shell
NODE_OPTIONS='--openssl-legacy-provider' npm run build
```

I get the same error, without the `libva` complaints

<details>
<summary>npm run start output</summary>

```javascript
> tuxedo-control-center@2.0.0 start
> electron ./dist/tuxedo-control-center

(node:35453) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (./dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:347:24)
    at ./dist/tuxedo-control-center/e-app/e-app/main.js:180:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:35453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C./node_modules/electron/dist/electron exited with signal SIGINT
```

</details>

**Comment by tuxedoder** [comment]
3.0.0 has node 24, closing issue.
