### ISSUE TITLE
Trying to build on GNU/Guix

### ISSUE THREAD

**Issue by minikN** [tuxedocomputers/tuxedo-control-center#241]
Hello, I'm trying to build TCC on GNU/Guix. after running `npm install`, I ran `npm run build-service`, this is the output:

```
>> npm run build-service

> tuxedo-control-center@1.2.2 build-service /home/db/.local/share/git/tuxedo-control-center
> tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service


> tuxedo-control-center@1.2.2 bundle-service /home/db/.local/share/git/tuxedo-control-center
> pkg --target node14-linux-x64 --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json

> pkg@4.5.1
> Warning Cannot find module 'TuxedoIOAPI' from '/home/db/.local/share/git/tuxedo-control-center/dist/tuxedo-control-center/service-app/native-lib'
  %1: /home/db/.local/share/git/tuxedo-control-center/dist/tuxedo-control-center/service-app/native-lib/TuxedoIOAPI.js
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at fabricate (/home/db/.local/share/git/tuxedo-control-center/node_modules/pkg/lib-es5/fabricator.js:134:15)
    at fabricateTwice (/home/db/.local/share/git/tuxedo-control-center/node_modules/pkg/lib-es5/fabricator.js:143:3)
    at MultiStream._queue (/home/db/.local/share/git/tuxedo-control-center/node_modules/pkg/lib-es5/producer.js:263:53)
    at MultiStream._next (/home/db/.local/share/git/tuxedo-control-center/node_modules/multistream/index.js:73:10)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@1.2.2 bundle-service: `pkg --target node14-linux-x64 --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tuxedo-control-center@1.2.2 bundle-service script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/db/.npm/_logs/2022-12-04T20_20_35_380Z-debug.log
ERROR: "bundle-service" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@1.2.2 build-service: `tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tuxedo-control-center@1.2.2 build-service script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/db/.npm/_logs/2022-12-04T20_20_35_395Z-debug.log
```
```
>> cat /home/db/.npm/_logs/2022-12-04T20_20_35_395Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/gnu/store/mgxvqphymkf1xfz4zryppr1jwnd5xcyw-node-14.19.3/bin/node',
1 verbose cli   '/gnu/store/5335c03njkwlhq5d2aqhimbssicskdcm-profile/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-service'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.19.3
4 verbose run-script [ 'prebuild-service', 'build-service', 'postbuild-service' ]
5 info lifecycle tuxedo-control-center@1.2.2~prebuild-service: tuxedo-control-center@1.2.2
6 info lifecycle tuxedo-control-center@1.2.2~build-service: tuxedo-control-center@1.2.2
7 verbose lifecycle tuxedo-control-center@1.2.2~build-service: unsafe-perm in lifecycle true
8 verbose lifecycle tuxedo-control-center@1.2.2~build-service: PATH: /gnu/store/mgxvqphymkf1xfz4zryppr1jwnd5xcyw-node-14.19.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/db/.local/share/git/tuxedo-control-center/node_modules/.bin:/gnu/store/5335c03njkwlhq5d2aqhimbssicskdcm-profile/bin:/gnu/store/5335c03njkwlhq5d2aqhimbssicskdcm-profile/sbin:/home/db/.nix-profile/bin:/home/db/.guix-home/profile/bin:/home/db/.guix-home/profile/sbin:/run/setuid-programs:/home/db/.config/guix/current/bin:/home/db/.guix-profile/bin:/run/current-system/profile/bin:/run/current-system/profile/sbin
9 verbose lifecycle tuxedo-control-center@1.2.2~build-service: CWD: /home/db/.local/share/git/tuxedo-control-center
10 silly lifecycle tuxedo-control-center@1.2.2~build-service: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service'
10 silly lifecycle ]
11 silly lifecycle tuxedo-control-center@1.2.2~build-service: Returned: code: 1  signal: null
12 info lifecycle tuxedo-control-center@1.2.2~build-service: Failed to exec build-service script
13 verbose stack Error: tuxedo-control-center@1.2.2 build-service: `tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/gnu/store/mgxvqphymkf1xfz4zryppr1jwnd5xcyw-node-14.19.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/gnu/store/mgxvqphymkf1xfz4zryppr1jwnd5xcyw-node-14.19.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid tuxedo-control-center@1.2.2
15 verbose cwd /home/db/.local/share/git/tuxedo-control-center
16 verbose Linux 5.15.79
17 verbose argv "/gnu/store/mgxvqphymkf1xfz4zryppr1jwnd5xcyw-node-14.19.3/bin/node" "/gnu/store/5335c03njkwlhq5d2aqhimbssicskdcm-profile/bin/npm" "run" "build-service"
18 verbose node v14.19.3
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error tuxedo-control-center@1.2.2 build-service: `tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service`
22 error Exit status 1
23 error Failed at the tuxedo-control-center@1.2.2 build-service script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'd appreciate any help!

**Comment by tuxedoder** [comment]
3.0.0 updated dependencies, open a new issue if you have issues.
