### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by FrancescoLucia** [tuxedocomputers/tuxedo-control-center#327]
I got an error during npm build command
`Compiling ngx-color-picker : es2015 as esm2015
10% building 4/5 modules 1 active ...kit/build-angular/src/angular-cli-files/models/es5-polyfills.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/francesco/Tuxedo/tuxedo-control-center/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/francesco/Tuxedo/tuxedo-control-center/node_modules/loader-runner/lib/LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:47:13)
    at processResource (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/Compilation.js:739:10)
    at /home/francesco/Tuxedo/tuxedo-control-center/node_modules/webpack/lib/Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
ERROR: "build-ng" exited with 1.
`

**Comment by benne3333** [comment]
Try compiling with NODE_OPTIONS=--openssl-legacy-provider

**Comment by FrancescoLucia** [comment]
Thank you. This works.
After compilation trying to start the app I got `electron: --openssl-legacy-provider is not allowed in NODE_OPTIONS
`, so it's necessary to unset NODE_OPTIONS.

**Comment by gagbo** [comment]
Hello,

In my opinion this should be added somewhere in the README, the solution here just saved me, and I still lost a lot of time until I tried to search in the repo issues for solutions

**Comment by tuxedoder** [comment]
The readme mentions to use node 14 for now which doesn't require this parameter.

**Comment by gagbo** [comment]
I see, I missed the info because I didn’t read the code sample that mentions 14, only the part that says that I need "nodejs"

Thanks
