### ISSUE TITLE
Version 2.1.1 does not work

### ISSUE THREAD

**Issue by BlackJohnny** [tuxedocomputers/tuxedo-control-center#335]
After upgrading to version 2.1.1 the Tuxedo Control Center does not function anymore.

Starting it from the command line it gives these errors:

```
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
(node:7026) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:568:24)
    at /opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/e-app/main.js:191:13
    at Generator.next (<anonymous>)
    at fulfilled (/opt/tuxedo-control-center/resources/app.asar/node_modules/tslib/tslib.js:164:62)
(Use `tuxedo-control-center --trace-warnings ...` to show where the warning was created)
(node:7026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Hardware info:

`TUXEDO InfinityBook Pro Gen8 with Nvidia`

Software info:

```
lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

uname -a
Linux tux 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by BlackJohnny** [comment]
PS: I have successfully built and run witout any issues the version 2.0.11

**Comment by Bundy01** [comment]
Hi,
I have the same problem with Arch:
```
(node:83565) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:568:24)
    at /opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/e-app/main.js:191:13
    at Generator.next (<anonymous>)
    at fulfilled (/opt/tuxedo-control-center/resources/app.asar/node_modules/tslib/tslib.js:164:62)
(Use `tuxedo-control-center --trace-warnings ...` to show where the warning was created)
(node:83565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:83565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: polyfills-es2015.1a9f9d639747f4800cb6.js:1:12102
```
The CPU frequency and its temperature are skyrocketing, the TCC process is at 100%.

**Comment by Bundy01** [comment]
@BlackJohnny,
unfortunately, it's not Wayland's fault. I use DE Cinnamon with Xorg.

**Comment by BlackJohnny** [comment]
Pls paste here the output for the `who` command. I have rebuilt the service and replaced the original one on my laptop and now it is functioning. But maybe there are multiple issues and maybe they are related to some dependency (perhaps node version). I am sure that the regex that I have changed did work previously because that file has not been modified recently.

**Comment by Bundy01** [comment]
`who` after freeze:
```sh
***       tty2         2023-12-20 15:05 (:0)
***       pts/0        2023-12-20 23:13 (l)
***       pts/1        2023-12-20 15:05 (l)
```

**Comment by tuxedoherbert** [comment]
Should be fixed with later releases that are made to fit the newest kernels, too.

**Comment by Anubarak** [comment]
I have the very same issue now with my Tuxedo Infinity Book.
When I start it I receive
```
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```
I installed the latest software versions.
Is there any way to fix this?
