### ISSUE TITLE
Unexpected crash on Pulse 14 (gen 3) running OpenSUSE tumbleweed 

### ISSUE THREAD

**Issue by saccarosium** [tuxedocomputers/tuxedo-control-center#339]
## Info

```sh
$ uname -rmpio
6.6.6-1-default x86_64 x86_64 x86_64 GNU/Linux
$ head -n 2 /etc/*-release
NAME="openSUSE Tumbleweed"
# VERSION="20231218"
```

- Computer model: [Pulse 14 gen 3](https://www.tuxedocomputers.com/en/TUXEDO-Pulse-14-Gen3)
- DE: Gnome 45
- package: `tuxedo-control-center` 
- source: `http://rpm.tuxedocomputers.com/opensuse/15.5`

## The problem

When I open the application it will open but it will close shortly after:

[Screencast from 2023-12-20 09-42-44.webm](https://github.com/tuxedocomputers/tuxedo-control-center/assets/96259932/c17e5702-b0b3-40d2-b192-19d269e29a28)

**Comment by konstantintutsch** [comment]
This issue also occurs on Fedora 39 with the Aura 15 Gen 2.

This is the terminal output when starting the TUXEDO Control Center (with `--trace-warnings`):
```
 $ tuxedo-control-center --trace-warnings
(node:5920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:568:24)
    at /opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/e-app/main.js:191:13
    at Generator.next (<anonymous>)
    at fulfilled (/opt/tuxedo-control-center/resources/app.asar/node_modules/tslib/tslib.js:164:62)
(Use `tuxedo-control-center --trace-warnings ...` to show where the warning was created)
(node:5920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The process doesn't exit after this output. I had to exit with Ctrl+C.

**Comment by BlackJohnny** [comment]
If you can build it yourself, you can check this fix: https://github.com/tuxedocomputers/tuxedo-control-center/pull/338

You only need to replace the tccd service file with the one you build.

**Comment by konstantintutsch** [comment]
The fix sadly does not work.

I successfully build your version and installed it, but the Control Center still outputs the same error.

**Comment by BlackJohnny** [comment]
sorry! :(

Being the same behavior, I think the error is caused by the same issue, calling `string.match` blocks the process and the service does not reach the sequence where it registers with dbus.

In my investigations the regex is freezing if the input is not matching. Strangely not for version 2.0.11, therefore I suspect it is something related to the regex engine used. I am not familiar with these frameworks to understand this behavior.

**Comment by konstantintutsch** [comment]
A possible to solution to this issue is downgrading NodeJS to versions 16.x.

For RPM and APT: [nodesource/distributions](https://github.com/nodesource/distributions)

**Comment by tuxedoder** [comment]
This error message implies that the tccd service is not active which is required to run tcc. That was also mentioned in https://github.com/tuxedocomputers/tuxedo-control-center/issues/212 and https://github.com/tuxedocomputers/tuxedo-control-center/issues/130. You can manually start tccd with `sudo /path/tccd --start`. 

Normally the tccd service should be active by default after installing the package and a reboot. Does this still happen after a clean install of tcc 2.1.7?
