### ISSUE TITLE
Tuxedo Control Center (UI?) is crashing.

### ISSUE THREAD

**Issue by ColiZei** [tuxedocomputers/tuxedo-control-center#412]
Hey!

Since the last update, the control center crashes regularly / the try icon dissapears.
If i start the tcc ui again it sometimes works and sometime crashes to after closing the application window or other application windows.

```sh
# System
OS: Fedora Linux 40 (Workstation Edition) x86_64
Host: TUXEDO InfinityBook Pro Gen7 (MK1) (Standard)
Kernel: Linux 6.10.8-200.fc40.x86_64
DE: GNOME 46.4
WM: Mutter (Wayland)
```

```sh
# Packages
$ dnf list installed | grep 'tuxedo'    
tuxedo-control-center.x86_64                         2.1.13-4                            @tuxedo                                               
tuxedo-drivers.noarch                                4.6.3-1                             @tuxedo   
```
```sh
# Logs
$ journalctl --boot | grep "tccd\|tuxedo-control-center"
Sep 12 07:50:53 [HOSTNAME] audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tccd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 12 07:50:53 [HOSTNAME] systemd[1]: Started tccd.service - TUXEDO Control Center Service.
Sep 12 07:50:53 [HOSTNAME] tccd[3436]: Starting daemon v2.1.13 (node: v14.20.0 arch: x64)
Sep 12 07:50:53 [HOSTNAME] tccd[3436]: tuxedo-io ver 0.3.9 [ interface: uniwill ]
Sep 12 07:50:53 [HOSTNAME] tccd[3436]: Filled missing settings with default: /etc/tcc/settings
Sep 12 07:50:54 [HOSTNAME] tccd[3436]: Detected white only keyboard backlight
Sep 12 07:50:54 [HOSTNAME] tccd[3436]: Applied charging profile 'balanced'
Sep 12 07:50:54 [HOSTNAME] tccd[3436]: Set display brightness to 40% (38400) on intel_backlight
Sep 12 07:50:54 [HOSTNAME] tccd[3436]: ODMPowerLimitWorker: Set ODM TDPs ["45 W","60 W"]
Sep 12 07:50:54 [HOSTNAME] tccd[3436]: Daemon started
Sep 12 07:56:59 [HOSTNAME] tuxedo-control-[6493]: The program 'tuxedo-control-center' received an X Window System error.

# Logs
$ journalctl --boot | grep "tuxedo"                     
Sep 12 07:50:52 [HOSTNAME] kernel: tuxedo_compatibility_check: loading out-of-tree module taints kernel.
Sep 12 07:50:52 [HOSTNAME] kernel: tuxedo_compatibility_check: module verification failed: signature and/or required key missing - tainting kernel
Sep 12 07:50:52 [HOSTNAME] kernel: tuxedo_keyboard: module init
Sep 12 07:50:52 [HOSTNAME] kernel: input: TUXEDO Keyboard as /devices/platform/tuxedo_keyboard/input/input25
Sep 12 07:50:53 [HOSTNAME] tccd[3436]: tuxedo-io ver 0.3.9 [ interface: uniwill ]
Sep 12 07:50:53 [HOSTNAME] dkms[3749]: Error! tuxedo-drivers/4.4.0 is broken! Missing the source directory or the symbolic link pointing to it.
Sep 12 07:50:53 [HOSTNAME] dkms[3750]: Error! tuxedo-drivers/4.5.2 is broken! Missing the source directory or the symbolic link pointing to it.
Sep 12 07:50:53 [HOSTNAME] dkms[3751]: Error! tuxedo-drivers/4.5.3 is broken! Missing the source directory or the symbolic link pointing to it.
Sep 12 07:50:53 [HOSTNAME] dkms[3753]: Error! tuxedo-drivers/4.6.1 is broken! Missing the source directory or the symbolic link pointing to it.
Sep 12 07:50:53 [HOSTNAME] dkms[3754]: Error! tuxedo-drivers/4.6.2 is broken! Missing the source directory or the symbolic link pointing to it.
Sep 12 07:51:15 [HOSTNAME] systemd[5801]: Started app-gnome-tuxedo\x2dcontrol\x2dcenter\x2dtray-6493.scope - Application launched by gnome-session-binary.
Sep 12 07:56:59 [HOSTNAME] tuxedo-control-[6493]: The program 'tuxedo-control-center' received an X Window System error.
Sep 12 07:56:59 [HOSTNAME] systemd[5801]: app-gnome-tuxedo\x2dcontrol\x2dcenter\x2dtray-6493.scope: Consumed 1.389s CPU time.
```

**Comment by ntavish** [comment]
I have the same issue.

**Comment by ntavish** [comment]
When I try to simply restart the service, that also does not work:

```
Oct 03 02:31:43 tuxedo-os tccd[118167]: Tccd Exception
Oct 03 02:31:43 tuxedo-os tccd[118167]: Error: Couldn't start daemon. It is probably already running
Oct 03 02:31:43 tuxedo-os tccd[118167]: Error: Couldn't start daemon. It is probably already running
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at TuxedoControlCenterDaemon.<anonymous> (/snapshot/build-release/dist/tuxedo-control-center/service-app/service-app/classes/TuxedoControlCenterDaemon.js)
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at Generator.next (<anonymous>)
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at fulfilled (/snapshot/build-release/node_modules/tslib/tslib.js)
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
Oct 03 02:31:43 tuxedo-os tccd[118167]:     at internal/main/run_main_module.js:17:47
Oct 03 02:31:43 tuxedo-os tccd[118173]: Stopping daemon..
Oct 03 02:31:48 tuxedo-os tccd[118173]: Tccd Exception
Oct 03 02:31:48 tuxedo-os tccd[118173]: Error: Failed to stop daemon
Oct 03 02:31:48 tuxedo-os tccd[118173]: Error: Failed to stop daemon
Oct 03 02:31:48 tuxedo-os tccd[118173]:     at TuxedoControlCenterDaemon.<anonymous> (/snapshot/build-release/dist/tuxedo-control-center/service-app/service-app/classes/TuxedoControlCenterDaemon.js)
Oct 03 02:31:48 tuxedo-os tccd[118173]:     at Generator.next (<anonymous>)
Oct 03 02:31:48 tuxedo-os tccd[118173]:     at fulfilled (/snapshot/build-release/node_modules/tslib/tslib.js)
```

**Comment by ColiZei** [comment]
Still not fixed.
After moving the window, it crashes.

[Screencast From 2024-11-28 13-09-11.webm](https://github.com/user-attachments/assets/69ec7a2c-1e72-4a7d-a37f-0b84885abe09)

It also crashes if i move a other window.

[Screencast From 2024-11-28 13-19-38.webm](https://github.com/user-attachments/assets/dce39655-303a-46c1-9d01-87b7267975d4)
