### ISSUE TITLE
Fan speed maxes out on power off/suspend

### ISSUE THREAD

**Issue by unterhimmel** [tuxedocomputers/tuxedo-control-center#420]
Using Tuxedo Aura 15 Gen1. OS is Ubuntu 24.04.1 LTS x86_64 and TCC version is 2.1.13. 

Sometimes when powering off/suspending my laptop, the fan speed suddenly maxes out until it is powered off/sleeping. It also happens when I suspend my laptop and immediately wake it (by accident by moving my mouse).

My fan speed config shouldn't go up that high normally, and the temperatures shown in TCC seem to be normal. This issue also does not occur on every power off/suspend, it seems to happen at random (I haven't found any correlation between occurrences).

**Comment by cmader** [comment]
I have exactly the same problem on an Infinitybook S15 Gen6 on Fedora 40. TCC fan control usually works fine, but the loud noises on shutdown are very annoying. I fixed this by creating a systemd unit file that gets executed right before shutdown and unloads the tuxedo_keyboard module.

**Comment by tuxedoder** [comment]
I did some testing and on my Aura 15 Gen 1 and IBS 15 Gen 6. I sometimes did notice some fan speed increase on sleep. Not 100% but some. The cause seems to be switching from manual to auto mode during `onExit()`. This is done for two reasons, so [laptops which are configured with the full fan mode properly wakeup from sleep](https://github.com/tuxedocomputers/tuxedo-control-center/issues/364#issuecomment-2026174663) and because stopping the tccd service at any point should set auto mode, otherwise the fans will keep the last set value at any temperature. Currently `tccd` stops when going into sleep and starts again on wakeup and can be manually stopped with `systemctl stop tccd`. I think that auto mode has enough time between sleep and `tccd` stop to configure the fan.

The Aura 15 Gen 1 doesn't use full fan mode to set the fans and removing  `ioAPI.setFansAuto()` in `onExit()` seemingly fixes the issue for that device.

If someone wants to test it, remove this line:
https://github.com/tuxedocomputers/tuxedo-control-center/blob/2fca7138a29e25d1496156f50426691001334404/src/service-app/classes/FanControlWorker.ts#L111

Build commands I use:
```
nvm i 14
nvm use 14
npm i
npm run pack-prod
```

But be aware that with this change `tccd` will never set the fans into auto mode. If `tccd` stops and fans are in manual mode, fans will use the last set value for all temperatures.

I am currently not sure how to handle this with all these requirements.

**Comment by bouederni** [comment]
@tuxedoder Apologies for the very late follow-up. When trying to build TCC with the build commands you provided, I get an error : 

```bash
spipo@spipos-laptop:~/tuxedo-control-center$ npm i

> abstract-socket@2.1.1 install /home/spipo/tuxedo-control-center/node_modules/abstract-socket
> node-gyp rebuild

make: Entering directory '/home/spipo/tuxedo-control-center/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/bindings/src/abstract_socket.o
In file included from ../../nan/nan.h:60,
                 from ../src/abstract_socket.cc:5:
/home/spipo/.cache/node-gyp/14.21.3/include/node/node.h:793:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/spipo/.cache/node-gyp/14.21.3/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/abstract_socket.cc:181:1: note: in expansion of macro ‘NODE_MODULE’
  181 | NODE_MODULE(abstract_socket, Initialize)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/home/spipo/tuxedo-control-center/node_modules/abstract-socket/build'

> usocket@1.0.1 install /home/spipo/tuxedo-control-center/node_modules/usocket
> node-gyp rebuild

make: Entering directory '/home/spipo/tuxedo-control-center/node_modules/usocket/build'
  CXX(target) Release/obj.target/uwrap/src/uwrap.o
  SOLINK_MODULE(target) Release/obj.target/uwrap.node
  COPY Release/uwrap.node
make: Leaving directory '/home/spipo/tuxedo-control-center/node_modules/usocket/build'

> core-js@3.6.4 postinstall /home/spipo/tuxedo-control-center/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /home/spipo/tuxedo-control-center/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> es5-ext@0.10.62 postinstall /home/spipo/tuxedo-control-center/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> @angular/cli@10.2.4 postinstall /home/spipo/tuxedo-control-center/node_modules/@angular/cli
> node ./bin/postinstall/script.js


> electron@13.6.9 postinstall /home/spipo/tuxedo-control-center/node_modules/electron
> node install.js

Error: end of central directory record signature not found
    at /home/spipo/tuxedo-control-center/node_modules/yauzl/index.js:187:14
    at Immediate.<anonymous> (/home/spipo/tuxedo-control-center/node_modules/yauzl/index.js:624:38)
    at processImmediate (internal/timers.js:464:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@13.6.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@13.6.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spipo/.npm/_logs/2025-02-26T15_40_14_555Z-debug.log
```

Here is the log file mentioned at the end : [2025-02-26T15_40_14_555Z-debug.log](https://github.com/user-attachments/files/18987981/2025-02-26T15_40_14_555Z-debug.log)

I tried reinstalling everything with no success. Let me know if you need me to do anything on my end.

**Comment by unterhimmel** [comment]
@tuxedoder Apologies for the very late follow-up. When trying to build TCC with the build commands you provided, I get an error : 

```bash
spipo@spipos-laptop:~/tuxedo-control-center$ npm i

> abstract-socket@2.1.1 install /home/spipo/tuxedo-control-center/node_modules/abstract-socket
> node-gyp rebuild

make: Entering directory '/home/spipo/tuxedo-control-center/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/bindings/src/abstract_socket.o
In file included from ../../nan/nan.h:60,
                 from ../src/abstract_socket.cc:5:
/home/spipo/.cache/node-gyp/14.21.3/include/node/node.h:793:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/spipo/.cache/node-gyp/14.21.3/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/abstract_socket.cc:181:1: note: in expansion of macro ‘NODE_MODULE’
  181 | NODE_MODULE(abstract_socket, Initialize)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/home/spipo/tuxedo-control-center/node_modules/abstract-socket/build'

> usocket@1.0.1 install /home/spipo/tuxedo-control-center/node_modules/usocket
> node-gyp rebuild

make: Entering directory '/home/spipo/tuxedo-control-center/node_modules/usocket/build'
  CXX(target) Release/obj.target/uwrap/src/uwrap.o
  SOLINK_MODULE(target) Release/obj.target/uwrap.node
  COPY Release/uwrap.node
make: Leaving directory '/home/spipo/tuxedo-control-center/node_modules/usocket/build'

> core-js@3.6.4 postinstall /home/spipo/tuxedo-control-center/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /home/spipo/tuxedo-control-center/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> es5-ext@0.10.62 postinstall /home/spipo/tuxedo-control-center/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> @angular/cli@10.2.4 postinstall /home/spipo/tuxedo-control-center/node_modules/@angular/cli
> node ./bin/postinstall/script.js


> electron@13.6.9 postinstall /home/spipo/tuxedo-control-center/node_modules/electron
> node install.js

Error: end of central directory record signature not found
    at /home/spipo/tuxedo-control-center/node_modules/yauzl/index.js:187:14
    at Immediate.<anonymous> (/home/spipo/tuxedo-control-center/node_modules/yauzl/index.js:624:38)
    at processImmediate (internal/timers.js:464:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@13.6.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@13.6.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spipo/.npm/_logs/2025-02-26T15_40_14_555Z-debug.log
```

Here is the log file mentioned at the end : [2025-02-26T15_40_14_555Z-debug.log](https://github.com/user-attachments/files/18987981/2025-02-26T15_40_14_555Z-debug.log)

I tried reinstalling everything with no success. Let me know if you need me to do anything on my end.

**Comment by unterhimmel** [comment]
whoops, looks like I accidentally closed the issue... Not super familiar with how GitHub issues work 😅

could this be undone? It says I can't reopen the issue

**Comment by unterhimmel** [comment]
I had closed the issue by accident. My mistake

**Comment by unterhimmel** [comment]
I tried installing on 3 separate networks and am still facing the same issue. 

I also tried running the install as root, clearing the npm cache, and other tips suggested by various StackOverflow articles and the install is still giving the same ELIFECYCLE error. Running as root gives two other errors during `npm install` which do not interrupt the install itself.

Keeps saying \ when I try to upload said logs within a text file... so here they are in full.
<details>
<summary><h2>My command line logs</h2></summary>

```bash
root@spipos-laptop:/home/spipo/tuxedo-control-center# npm i --unsafe-perm=true

> abstract-socket@2.1.1 install /home/spipo/tuxedo-control-center/node_modules/abstract-socket
> node-gyp rebuild

Traceback (most recent call last):
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.11.0-109018-tuxedo
gyp ERR! command "/root/.nvm/versions/node/v14.21.3/bin/node" "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/spipo/tuxedo-control-center/node_modules/abstract-socket
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 

> usocket@1.0.1 install /home/spipo/tuxedo-control-center/node_modules/usocket
> node-gyp rebuild

Traceback (most recent call last):
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.11.0-109018-tuxedo
gyp ERR! command "/root/.nvm/versions/node/v14.21.3/bin/node" "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/spipo/tuxedo-control-center/node_modules/usocket
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 

> core-js@3.6.4 postinstall /home/spipo/tuxedo-control-center/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /home/spipo/tuxedo-control-center/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> es5-ext@0.10.62 postinstall /home/spipo/tuxedo-control-center/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> @angular/cli@10.2.4 postinstall /home/spipo/tuxedo-control-center/node_modules/@angular/cli
> node ./bin/postinstall/script.js


> electron@13.6.9 postinstall /home/spipo/tuxedo-control-center/node_modules/electron
> node install.js


> tuxedo-control-center@2.1.16 install /home/spipo/tuxedo-control-center
> node-gyp rebuild

Traceback (most recent call last):
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.11.0-109018-tuxedo
gyp ERR! command "/root/.nvm/versions/node/v14.21.3/bin/node" "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/spipo/tuxedo-control-center
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@2.1.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-03-01T09_06_36_212Z-debug.log








---








root@spipos-laptop:/home/spipo/tuxedo-control-center# npm run pack-prod 

> tuxedo-control-center@2.1.16 pack-prod /home/spipo/tuxedo-control-center
> run-s build-prod && npm run electron-builder


> tuxedo-control-center@2.1.16 build-prod /home/spipo/tuxedo-control-center
> run-s clean build-electron build-native build-service build-ng-prod copy-files


> tuxedo-control-center@2.1.16 clean /home/spipo/tuxedo-control-center
> rm -rf ./dist; rm -rf ./build; rm -rf ./usr


> tuxedo-control-center@2.1.16 build-electron /home/spipo/tuxedo-control-center
> tsc -p ./src/e-app


> tuxedo-control-center@2.1.16 build-native /home/spipo/tuxedo-control-center
> node-gyp configure && node-gyp rebuild

Traceback (most recent call last):
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.11.0-109018-tuxedo
gyp ERR! command "/root/.nvm/versions/node/v14.21.3/bin/node" "/root/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /home/spipo/tuxedo-control-center
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@2.1.16 build-native: `node-gyp configure && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@2.1.16 build-native script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-03-01T09_07_57_518Z-debug.log
ERROR: "build-native" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@2.1.16 build-prod: `run-s clean build-electron build-native build-service build-ng-prod copy-files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@2.1.16 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-03-01T09_07_57_549Z-debug.log
ERROR: "build-prod" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@2.1.16 pack-prod: `run-s build-prod && npm run electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@2.1.16 pack-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-03-01T09_07_57_578Z-debug.log
```
</details>

Apologies for using this GitHub issue to seek help for this seemingly entirely different issue. I can create a new issue for this if preferable.

**Comment by unterhimmel** [comment]
Turns out everything works just fine after a `chown` to myself of `~/.npm` as well as the TCC source folder... I feel a bit stupid 😅

After installation, your fix indeed seems to work properly. Thanks a lot for your assistance!

**Comment by minhperry** [comment]
Problem still persists for me on Fedora 44 KDE on a Gigabyte G5 MD, which should be Tuxedo-compatible.

tcc 3.0.6, driver 4.22.3-1.fc43
